# Catppuccin Mocha colors
thm_bg="#1e1e2e"
thm_fg="#cdd6f4"
thm_cyan="#89dceb"
thm_black="#181825"
thm_gray="#313244"
thm_magenta="#cba6f7"
thm_pink="#f5c2e7"
thm_red="#f38ba8"
thm_green="#a6e3a1"
thm_yellow="#f9e2af"
thm_blue="#89b4fa"
thm_orange="#fab387"
thm_black4="#585b70"

set -g status "on"
set -g status-position top
set -g status-justify "left"
set -g status-style "bg=default,fg=${thm_fg}"

set -g status-left-length "100"
set -g status-right-length "100"

# Status left
# Session name
set -g status-left "#[fg=${thm_bg},bg=${thm_blue},bold]  #S #[fg=${thm_blue},bg=default,nobold,nounderscore,noitalics] #[fg=${thm_red},bg=default,bold]#{?client_prefix,󱐋 ,}"

# Status right
# Host, Date, Time
set -g status-right "#[fg=${thm_pink},bg=default,nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_pink},bold] 󰒋 #h #[fg=${thm_pink},bg=default,nobold,nounderscore,noitalics] #[fg=${thm_yellow},bg=default,nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_yellow},bold] 󰃭 %Y-%m-%d #[fg=${thm_yellow},bg=default,nobold,nounderscore,noitalics] #[fg=${thm_green},bg=default,nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_green},bold] 󱑒 %H:%M #[fg=${thm_green},bg=default,nobold,nounderscore,noitalics]"

# Window status
setw -g window-status-format "#[fg=${thm_fg},bg=default]  #I #W  "
setw -g window-status-current-format "#[fg=${thm_magenta},bg=default,nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_magenta},bold] #I #W #[fg=${thm_magenta},bg=default,nobold,nounderscore,noitalics]"

# Modes
setw -g mode-style "fg=${thm_pink} bg=${thm_black4} bold"
set -g message-style "fg=${thm_cyan} bg=${thm_gray} align=centre"
set -g message-command-style "fg=${thm_cyan} bg=${thm_gray} align=centre"

# Panes
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_blue}"

# Windows
setw -g window-status-activity-style "fg=${thm_fg},bg=default,none"
setw -g window-status-separator ""
setw -g window-status-style "fg=${thm_fg},bg=default,none"
