# -- Prefix
set-option -g prefix C-t
unbind C-b
bind-key C-t send-prefix

# -- Options
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -s escape-time 0
set -g focus-events on
set -g status-interval 5
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g mouse on

# -- Key Bindings
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Reload
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Split window
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Navigate panes
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Resize panes
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Productivity
bind-key -r i run-shell "tmux neww tmux-cht.sh"
bind-key -r f run-shell "tmux neww tmux-sessionizer"

# -- Theme (Catppuccin Mocha)
source-file ~/.config/tmux/statusline.conf
